import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Printer } from "lucide-react";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//colocar imagem da logo smec

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-blue-50 flex flex-col items-center`}
      >
        <div className="flex flex-col items-center justify-center text-center p-8">
          <div className="flex gap-2">
            <div className="bg-blue-500 rounded-full p-2 h-fit w-fit mr-2">
              <Printer className="w-10 h-10 text-white"/>
            </div>
            <div className=" flex flex-col justify-center items-center space-y-5">
              <h1 className="text-5xl font-bold text-black">Sistema de Controle de Impressões</h1>
              <p className="text-2xl text-gray-600 font-medium">Gerencie e monitore as impressões das escolas</p>
            </div>
          </div>
          <div className="flex mt-5">
            <Navbar/>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
